[Config]
ConfigVersion = "0.10.5"
Enabled = true
ToggleButton = "F11"
PreferredMaxTextureDimension = 8192
RequiredFreeMemory = 64
RequiredFreeMemoryHysterisis = 1.5
GarbageCollectAccountUnownedTextures = true
GarbageCollectAccountOwnedTexture = true
LeakPreventTexture = true
LeakPreventAll = true
DiscardDuplicates = false
DiscardDuplicatesFrameDelay = 2
DiscardDuplicatesBlacklist = ["LooseSprites\\Cursors", "Minigames\\TitleButtons"]
[Config.Debug.Logging]
LogInfo = true
LogWarnings = true
LogErrors = true
[Config.DrawState]
SetLinear = true
EnableMSAA = true
DisableDepthBuffer = false
BackbufferFormat = "Color"
[Config.Resample]
EnableDynamicScale = true
TrimWater = true
ScaleBias = 0.1000000014901161
MaxScale = 6
MinimumTextureDimensions = 4
EnableWrappedAddressing = true
UseBlockCompression = true
BlockCompressionQuality = "Highest"
BlockHardAlphaDeviationThreshold = 7
Blacklist = ["LooseSprites\\Lighting\\"]
[Config.Resample.Padding]
Enabled = true
MinimumSizeTexels = 4
IgnoreUnknown = false
StrictList = ["LooseSprites\\Cursors"]
Whitelist = ["LooseSprites\\font_bold", "Characters\\Farmer\\hairstyles", "Characters\\Farmer\\pants", "Characters\\Farmer\\shirts", "TileSheets\\weapons", "TileSheets\\bushes", "TerrainFeatures\\grass", "TileSheets\\debris", "TileSheets\\animations", "Maps\\springobjects", "Maps\\summerobjects", "Maps\\winterobjects", "Maps\\fallobjects", "Buildings\\houses", "TileSheets\\furniture", "TerrainFeatures\\tree1_spring", "TerrainFeatures\\tree2_spring", "TerrainFeatures\\tree3_spring", "TerrainFeatures\\tree1_summer", "TerrainFeatures\\tree2_summer", "TerrainFeatures\\tree3_summer", "TerrainFeatures\\tree1_fall", "TerrainFeatures\\tree2_fall", "TerrainFeatures\\tree3_fall", "TerrainFeatures\\tree1_winter", "TerrainFeatures\\tree2_winter", "TerrainFeatures\\tree3_winter"]
Blacklist = []
[Config.WrapDetection]
edgeThreshold = 0.2000000029802322
alphaThreshold = 1
[Config.AsyncScaling]
Enabled = true
EnabledForUnknownTextures = false
[Config.MemoryCache]
Enabled = true
AlwaysFlush = false
Type = "LZ"
Async = true
[Config.Cache]
Enabled = true
